"""Clan codes generated by the server: 'CLAN-' followed by 8 random characters.

The alphabet leaves out the characters people confuse when they read a code aloud or copy it by
hand (I, L, O, 0, 1): 31 characters, so 31^8 (about 8.5e11, roughly 39 bits) codes. The random
source is `secrets`. A code that is already taken is simply drawn again (the use case retries).
"""

from __future__ import annotations

import secrets

CLAN_CODE_PREFIX = "CLAN-"
CLAN_CODE_LENGTH = 8
CLAN_CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"


def generate_clan_code() -> str:
    return CLAN_CODE_PREFIX + "".join(secrets.choice(CLAN_CODE_ALPHABET) for _ in range(CLAN_CODE_LENGTH))
